---

- name: Clean up Xcode XIP
  become: true
  command:
    argv:
      - rm
      - -f
      - /Applications/Xcode_{{ xcode_version }}.xip
      - /tmp/install-xcode.sh
  listen: clean-up-xcode-install
