---

- name: Check Developer Mode
  command:
    argv:
      - /usr/sbin/DevToolsSecurity
      - -status
  register: dev_tools_security
  changed_when: false

- name: Set xcode_developer_mode_enabled
  set_fact:
    xcode_developer_mode_enabled: "{{ dev_tools_security.stdout.find('enabled') != -1 }}"

- name: Enable Developer Mode
  become: true
  command:
    argv:
      - /usr/sbin/DevToolsSecurity
      - -enable
  when: not xcode_developer_mode_enabled

- name: Set Xcode name
  set_fact:
    xcode_name: Xcode_{{ xcode_version }}.app
    xcode_xip_name: Xcode_{{ xcode_version }}.xip

- name: Set Xcode path
  set_fact:
    xcode_path: /Applications/{{ xcode_name }}
    xcode_downloads_dir: /Users/{{ ansible_user }}/Downloads

- name: Check if Xcode is already installed
  stat:
    path: "{{ xcode_path }}"
  register: xcode

- when: not xcode.stat.exists
  block:
    - name: Download Xcode XIP
      get_url:
        url: "{{ xcode_xip_base_url }}/{{ xcode_xip_name }}"
        dest: "{{ xcode_downloads_dir }}/{{ xcode_xip_name }}"
        mode: 'u=rw,g=r,o=r'
      notify: clean-up-xcode-xip

    # Although the XIP contains the Xcode version in its name, it always expands to a generic 'Xcode.app' bundle.
    - name: Expand Xcode XIP
      become: true
      command:
        argv:
          - /usr/bin/xip
          - --expand
          - "{{ xcode_xip_name }}"
        chdir: "{{ xcode_downloads_dir }}"
      poll: 60
      async: "{{ xcode_xip_extraction_timeout }}" # Prevent SSH connections timing out waiting for extraction

    # Move and rename the generic 'Xcode.app'
    - name: Move Xcode under /Applications
      become: true
      command:
        argv:
          - /bin/mv
          - Xcode.app
          - "{{ xcode_path  }}"
        chdir: "{{ xcode_downloads_dir }}"

    - name: Accept Xcode license
      become: true
      command:
        argv:
          - "{{ xcode_path }}/Contents/Developer/usr/bin/xcodebuild"
          - -license
          - accept
      poll: 60
      async: "{{ xcode_accept_licence_timeout }}" # Prevent SSH connections timing out waiting for extraction

    - name: Select Xcode
      become: true
      command:
        argv:
          - /usr/bin/xcode-select
          - --switch
          - "{{ xcode_path }}"
