---

- name: Provision Build VM
  hosts: default
  tasks:
    - name: Add SSH key
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ packer_ssh_public_key }}"

    - name: Disable Software Updates
      import_role:
        name: disable-software-updates

    - name: Install Homebrew
      import_role:
        name: install-homebrew

    - name: Install jq
      get_url:
        url: https://github.com/stedolan/jq/releases/download/{{ jq_version }}/jq-osx-amd64
        dest: /usr/local/bin/jq
        mode: 'u=rwx,g=rx,o=rx'

    - name: Install Xcode
      import_role:
        name: install-xcode
